### ISSUE TITLE
BadAuthentication on Login Attempt

### ISSUE THREAD

**Issue by ErickSumargo** [theapache64/stackzy#69] opened 2021-07-17 10:48 UTC
`java --version`: 15.0.2
stackzy version: 1.0.7

Cool app and nice UI! But...

Issue:
Created new Google account as suggested but always get `BadAuthentication` status when trying to login.

**Comment by sk123411** [comment] 2021-07-24 03:44
Yes getting the same issue, Bad authentication every time when try to login

**Comment by theapache64** [comment] 2021-07-24 06:45
@ErickSumargo @sk123411 

This is caused by an unexpected change in playstore API. Will be fixed in 1.0.8 :+1: 
Thanks for reporting :innocent:

**Closed** 2021-07-24 07:17 UTC
Labels: bug, critical

**Comment by theapache64** [comment] 2021-07-24 07:44
@ErickSumargo @sk123411 @ananthakrishnankr

You can download v1.0.8 from [here](https://github.com/theapache64/stackzy/releases/tag/1.0.8)

**Comment by sk123411** [comment] 2021-07-24 11:38
Thanks for the quick response and fix!! :):)  Well i have came another issue when try to decompile apps from playstore 
<img width="900" alt="err" src="https://user-images.githubusercontent.com/37469719/126867235-44e30182-c401-4026-a549-9145d0a40d74.PNG">

**Comment by theapache64** [comment] 2021-07-24 12:21
@sk123411 Which app is this?

**Comment by sk123411** [comment] 2021-07-24 16:51
Getting the same error in all the apps which i am searching on playstore , the libraries(beta) and .apk feature are working fine, i am using it on windows

**Comment by theapache64** [comment] 2021-07-24 16:51
@sk123411 Can you give me the output of `java -version` ?

**Comment by sk123411** [comment] 2021-07-24 17:01
Java not installed on my system

**Comment by theapache64** [comment] 2021-07-24 17:03
That could be the problem. Because we need JDK to decompile the app. Are you able to decompile apps via ADB ?

**Comment by sk123411** [comment] 2021-07-27 04:29
thanks its working now! kudos to your hardwork
